/*
 * civ_aliases.c - Resolved function aliases
 * AUTO-GENERATED by resolve_stubs.py
 *
 * These functions were called by name but actually map
 * to existing recompiled functions.
 */

#include "recomp/cpu.h"

/* Near-call aliases for far functions lifted from dump */
extern void far_085F_141F(CPU *cpu);
extern void far_085F_1724(CPU *cpu);

void res_009A0F(CPU *cpu) { far_085F_141F(cpu); }
void res_009D14(CPU *cpu) { far_085F_1724(cpu); }

/* Near-call aliases for functions that conflict with far versions
 * These functions are compiled as FAR in the original code (in overlaid segments).
 * Near callers push only 2-byte return address, but the function does far return (sp+=4).
 * We compensate by pushing an extra 2 bytes before calling the far version.
 */
extern void far_1B05_144C(CPU *cpu);
extern void far_1B05_14D4(CPU *cpu);
extern void far_1F67_01AD(CPU *cpu);
extern void far_1F67_0471(CPU *cpu);
extern void far_1F67_0000(CPU *cpu);

void res_01C49C(CPU *cpu) { push16(cpu, cpu->cs); far_1B05_144C(cpu); }
void res_01C524(CPU *cpu) { push16(cpu, cpu->cs); far_1B05_14D4(cpu); }
void res_01F81D(CPU *cpu) { push16(cpu, cpu->cs); far_1F67_01AD(cpu); }
void res_01FAE1(CPU *cpu) { push16(cpu, cpu->cs); far_1F67_0471(cpu); }
void res_01F670(CPU *cpu) { push16(cpu, cpu->cs); far_1F67_0000(cpu); }
