/*
 * civ_aliases.c - Resolved function aliases
 * AUTO-GENERATED by resolve_stubs.py
 *
 * These functions were called by name but actually map
 * to existing recompiled functions.
 */

#include "recomp/cpu.h"
#include <stdio.h>

/* Near-call aliases for far functions lifted from dump */
extern void far_085F_141F(CPU *cpu);
extern void far_085F_1724(CPU *cpu);

void res_009A0F(CPU *cpu) { far_085F_141F(cpu); }
void res_009D14(CPU *cpu) { far_085F_1724(cpu); }

/* Near-call aliases for functions that conflict with far versions
 * These functions are compiled as FAR in the original code (in overlaid segments).
 * Near callers push only 2-byte return address, but the function does far return (sp+=4).
 * We compensate by pushing an extra 2 bytes before calling the far version.
 */
extern void far_1B05_144C(CPU *cpu);
extern void far_1B05_14D4(CPU *cpu);
extern void far_1F67_01AD(CPU *cpu);
extern void far_1F67_0471(CPU *cpu);
extern void far_1F67_0000(CPU *cpu);

void res_01C49C(CPU *cpu) { push16(cpu, cpu->cs); far_1B05_144C(cpu); }
void res_01C524(CPU *cpu) { push16(cpu, cpu->cs); far_1B05_14D4(cpu); }
void res_01F81D(CPU *cpu) { push16(cpu, cpu->cs); far_1F67_01AD(cpu); }
void res_01FAE1(CPU *cpu) { push16(cpu, cpu->cs); far_1F67_0471(cpu); }
void res_01F670(CPU *cpu) { push16(cpu, cpu->cs); far_1F67_0000(cpu); }

/* Thunk table aliases - thunks resolved to overlay functions.
 * The thunk table at 0x0761 has 7-byte entries indexed by overlay function.
 * Entry# = (offset - 0x0761) / 7. Mapping: OVL functions in order across overlays.
 */
extern void ovl02_02CDD7(CPU *cpu);  /* entry 2 */
extern void ovl02_02D72A(CPU *cpu);  /* entry 3 */
extern void ovl03_02E45D(CPU *cpu);  /* entry 12 */
extern void ovl05_02FFC2(CPU *cpu);  /* entry 19 */
extern void ovl05_0307DA(CPU *cpu);  /* entry 21 */
extern void ovl07_0349D4(CPU *cpu);  /* entry 38 */
extern void ovl12_03D15C(CPU *cpu);  /* entry 91 */

/* far_0000_076F is NOT ovl02_02CDD7 (that alias caused infinite recursion:
 * the civ-select dialog ovl02_02CDD7 calls 0x076F 24x in a grid loop, so
 * aliasing it to itself re-entered the whole dialog every iteration, dropping
 * SP ~0x258/level until the stack/FILE area was exhausted). The thunk-table
 * 0x0761 entries are runtime-patched from per-overlay descriptors, so the
 * naive "overlay functions in order" assignment is unreliable. 0x076F is a
 * screen-grab primitive: far_076F(flag, x, y, w, h) captures a w*h rect and
 * returns a sprite handle later blitted by far_0000_083F. Hand-implemented in
 * civ_impl.c. See session log 2026-05-30. */
/* far_0000_0776 was MIS-ALIASED to ovl02_02D72A (a full-screen builder that
 * fills 320x200 + loads a PIC) — wrong for a 7-arg per-civ stat/value renderer;
 * it spun the civ-select leader loop (ovl05_030C49) on civ 5's data. Stub as a
 * no-op far ret (cosmetic stat draw) to unblock; caller cleans the 7 args. */
void far_0000_0776(CPU *cpu) { cpu->sp += 4; }
/* far_0000_07B5 was MIS-ALIASED to ovl03_02E45D (a full-screen white-fill) by
 * resolve_stubs.py's proximity heuristic — but it's the menu's "text line-height"
 * query: res_01D221 stores its return in [0x2F54] (the item height, divided by in
 * the click handler) and special-cases 9. The bad alias painted every menu screen
 * full white. The menu uses the built-in 8x8 font (far_0000_077D char-width=8), so
 * return 9 (the code subtracts 1 -> 8px line spacing). Takes 1 arg (font/style),
 * caller cleans it; far ret. */
void far_0000_07B5(CPU *cpu) { cpu->ax = 9; cpu->sp += 4; }
/* far_0000_07E6 is the PIC row blitter (src linear buffer -> dst page row),
 * NOT ovl05_02FFC2 (which mis-used arg1 as a page index). Implemented in
 * civ_impl.c. See session 2026-06-01 §10. */
/* far_0000_07F4 is the string renderer (called by res_001828), NOT
 * ovl05_0307DA — the sequential thunk assignment mis-mapped it. Hand-
 * implemented as an 8x8 text blit in civ_impl.c. See session 2026-05-31. */
void far_0000_086B(CPU *cpu) { ovl07_0349D4(cpu); }
/* far_0000_09DE is the blocking keyboard read (called by getkey far_1D1F_0AC9),
 * NOT ovl12_03D15C (a score-string builder the link-order alias mis-assigned).
 * Hand-implemented in civ_impl.c. See session 2026-06-01. */
